import type { AuthRequest, OAuthHelpers } from '@cloudflare/workers-oauth-provider';

/**
 * Per-user properties carried end-to-end-encrypted by the OAuth provider.
 *
 * After a successful Auth0 login these are attached to the grant (and to each
 * minted MCP access token) via `completeAuthorization({ props })`. The McpAgent
 * reads them from `this.props` and uses `upstreamAccessToken` as the Bearer
 * token when calling the Tribeunal API, so every tool call runs AS the logged-in
 * human.
 */
export interface UserProps {
  /** Auth0 `sub` claim — stable per-user identity (e.g. `google-oauth2|123`). */
  sub: string;
  /** User email from the Auth0 id_token, if present. */
  email?: string;
  /** Auth0 access token (audience = AUTH0_AUDIENCE) forwarded to the API. */
  upstreamAccessToken: string;
  /** Auth0 refresh token (requires `offline_access`); used to refresh the above. */
  upstreamRefreshToken?: string;
  /** Upstream access-token lifetime in seconds, mirrored onto the MCP token TTL. */
  upstreamExpiresIn?: number;
  /** Index signature so the props satisfy the provider's `Record<string, unknown>`. */
  [key: string]: unknown;
}

/**
 * Cloudflare bindings + non-secret vars + Auth0 secrets available to the worker.
 *
 * This is the SINGLE source of truth generated by `wrangler types` from
 * `wrangler.jsonc` + the secret names (`worker-configuration.d.ts`):
 *   Bindings:  OAUTH_KV (KV), MCP_OBJECT (Durable Object)
 *   Vars:      TRIBEUNAL_API_BASE_URL, AUTH0_SCOPE
 *   Secrets:   AUTH0_DOMAIN, AUTH0_CLIENT_ID, AUTH0_CLIENT_SECRET,
 *              AUTH0_AUDIENCE, COOKIE_ENCRYPTION_KEY
 *
 * Aliasing `Cloudflare.Env` keeps the worker in lockstep with the deployed
 * config and satisfies `McpAgent<Env>`'s `Env extends Cloudflare.Env` bound.
 * Re-run `wrangler types` after editing `wrangler.jsonc`.
 */
export type Env = Cloudflare.Env;

/** The Hono binding type for the OAuth `defaultHandler` app. */
export type HonoEnv = { Bindings: Env & { OAUTH_PROVIDER: OAuthHelpers } };

export type { AuthRequest };
